{
	"config": "core",
	"namespace": "\erdiko\modules",
	"modules": [
		"file": {
			"name": "file",
			"class":  "File",
			"active": 1
		  },
		"memcache": {
			"name": "memcache",
			"class":  "Memcache",
			"active": 1
		  },
		"cache": {
			"name": "cache",
			"class":  "Cache",
			"active": 1
		  },
		"facebook": {
			"name": "file",
			"class":  "File",
			"active": 1
		  },
		"facebook": {
			"name": "file",
			"class":  "File",
			"active": 1
		  }
    ]
}