<p>Thank you for visiting our site.</p>
<p>&nbsp;</p>

<form id="login" name="login-form" method="post" action="login/submit">
  <fieldset>
    <legend>Login to RSVP</legend>
for the Pandey / Arroyo Wedding
<p>
      <label for="code">Enter your RSVP Code</label>
      <input type="text" name="code" id="code" />
    </p>
<p>	
  	<input type="submit" name="Submit" id="Submit" value="Submit" />
</p>
    <p>&nbsp;</p>
  </fieldset>
</form>