<form id="rsvp-form" name="rsvp-form" method="post" action="form/submit">
  <fieldset>
    <legend>RSVP</legend>
    <p>Welcome <?php echo $data['guest']['name']; ?></p>
    <p>How many guests do you wish to RSVP?
      <label for="num_guests"></label>
      <select name="num_guests" id="num_guests">
        <option value="0">0 (cannot attend)</option>
    <?php
    for($i = 1; $i <= $data['guest']['num_rsvps']; $i++)
      echo '<option value="'.$i.'">'.$i.'</option>';
    ?>
      </select>
    </p>

  <div id="guest-num-rsvps"></div>

  <input type="submit" id="submit" value="submit">

    <p>&nbsp;</p>
  </fieldset>
</form>



<!-- TODO: move this to the footer.phtml -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="/app/theme/rsvp/js/rsvp.js"></script>