<form id="rsvp-form" name="rsvp-form" method="post" action="form/submit">
  <fieldset>
    <legend>RSVP</legend>
    <p>Welcome <?php echo $data['guest']['name']; ?></p>
    <p>How many guests do you wish to RSVP? 
      <label for="num_guests"></label>
      <select name="num_guests" id="num_guests">
      	<option value="0">0 (cannot attend)</option>
		<?php
		for($i = 1; $i <= $data['guest']['num_rsvps']; $i++)
			echo '<option value="'.$i.'">'.$i.'</option>';
		?>
      </select>
    </p>

	<?php
	for($i = 1; $i <= $data['guest']['num_rsvps']; $i++)
	{
		echo '<p>Guest '.$i.'
	      		<label for="guest'.$i.'">Name</label>
	      		<input type="text" name="guest'.$i.'" id="guest'.$i.'" alt="Full Name"/>
	    	</p>';
	}
	?>
	
	<input type="submit" id="submit" value="submit">
	
    <p>&nbsp;</p>
  </fieldset>
</form>