<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?php echo $data->getTitle(); ?></title>

    <link rel='stylesheet' href='<?php echo $this->getThemeUrl(); ?>/css/global.css' type='text/css' />

</head>
<body>

<div class="header-bg">
    <?php echo $data->getHeader(); ?>
</div>
<div class="container">
    <?php echo $this->getLayout(); ?>
</div>
<div class="footer-bg">
    <?php echo $data->getFooter(); ?>
</div>

</body>
</html>