// Prod
{
	"parent": "core",
	"config": "prod",
	"namespace": "\app\modules",
	"modules": [
		"magento": {
			"name": "magento",
			"folder": "contrib",
			"class":  "Magento",
			"active": 1
		  },
		"drupal": {
			"name": "drupal",
			"folder": "contrib",
			"class":  "Drupal",
			"active": 1
		  }
    ]
}

// Dev
{
	"parent": "prod",
	"config": "dev",
	"namespace": "\erdiko\modules",
	"modules": [
		"magento": {
			"name": "magento",
			"class":  "Magento",
			"active": 0
		  }
    ]
}
