{
	"name": "default",
	"namespace": "\erdiko\theme\default",
	"path": "/erdiko/theme/default",
	"css": [
		{
			"name": "global",
			"file":  "/erdiko/theme/default/css/global.css",
			"active": 1
		}
	],
	"js": [
		{
			"name": "jquery",
			"file":  "/libraries/javascript/jquery-1.7.2.js",
			"active": 1
		},
		{
			"name": "global",
			"file":  "/erdiko/theme/default/js/global.js",
			"active": 1
		}
	],
	"templates": {
		"page": {
			"file": "/erdiko/theme/default/templates/page.phtml"
		},
		"footer": {
			"file": "/erdiko/theme/default/templates/footer.phtml"
		},
		"header": {
			"file": "/erdiko/theme/default/templates/header.phtml"	
		},
		"home": {
			"file": "/erdiko/theme/default/templates/home.phtml"
		},
		"layout-1": {
			"file": "/erdiko/theme/default/templates/layout-1.phtml"
		},
		"layout-2": {
			"file": "/erdiko/theme/default/templates/layout-2.phtml"
		},
		"layout-3": {
			"file": "/erdiko/theme/default/templates/layout-3.phtml"
		}
	}
}