{
	"name": "rsvp",
	"namespace": "\app\contexts\rsvp",
	"path": "/app/contexts/rsvp",
	"parent": "/erdiko/theme/default/theme.inc",
	"coulmns": 1,
	"css": [
		{
			"name": "rsvp",
			"file":  "/app/contexts/rsvp/css/rsvp.css",
			"active": 1
		}
	],
	"js": [
		{
			"name": "rsvp",
			"file":  "/app/contexts/rsvp/js/rsvp.js",
			"active": 1
		}
	],
	"templates": {
		"footer": {
			"file": "/app/contexts/rsvp/views/footer.phtml"
		},
		"header": {
			"file": "/app/contexts/rsvp/views/header.phtml"	
		},
		"page": {
			"file": "/app/contexts/rsvp/views/page.phtml"	
		}
	}
}