<!DOCTYPE html>
<!-- This template is based on the slim skeleton, https://github.com/slimphp/Slim-Skeleton -->
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Erdiko II</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }
            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Lumberjack</h1>
        <div>Erdiko Powered Logger</div>
        <p><a href="/log">View Logs</a>
    </body>
</html>
