<?php error_log('data: '.print_r($data, true)); ?>

<h1><?php echo $data['title']; ?></h1>
<h2>Hi <?php echo $data['guest']['name']; ?></h2>
<p><?php echo $data['description']; ?></p>
<p>&nbsp;</p>

<form id="confirmation-form" name="confirmation-form" method="post" action="/form/confirm">
  <fieldset>
    <legend>RSVP Review</legend>
	
	<?php
	if( $data['guest']['accept'] == 0 )
	{
		echo "<h3>You are not attending.</h3>";
	}
	else
	{
		echo "<h3>You have RSVP'ed the following guests</h3>";
		
		for($i = 0; $i < count($data['guests']); $i++)
		{
			$ii = $i+1;
			$data['guests'][$i]['name'];
			echo '<p>Guest '.$ii.': '.$data['guests'][$i]['name'].'</p>';
		}
	}
	?>
	
    <p>&nbsp;</p>
  </fieldset>
</form>
